sonar.projectKey=Andriiklymiuk_corgi
sonar.organization=corgi
sonar.projectName=corgi
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**,corgi_vscode_extension/**,corgi_services/**,templates/**,docs/**,packaging/**,plugins/**,resources/**,dump.bak,install.sh,install.ps1,Dockerfile,**/*.md

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/*_test.go,main.go,cmd/docs.go,cmd/completion.go,cmd/upgrade.go,utils/art/**,utils/messages.go,utils/getRandomQuote.go,utils/proc_windows.go,utils/sendInterrupt_windows.go
