sonar.projectKey=Andriiklymiuk_corgi
sonar.organization=corgi
sonar.projectName=corgi
sonar.sourceEncoding=UTF-8

sonar.sources=.
sonar.exclusions=**/*_test.go,**/vendor/**,**/testdata/**,corgi_vscode_extension/**,corgi_services/**,templates/**,docs/**,packaging/**,plugins/**,resources/**,dump.bak,install.sh,install.ps1,Dockerfile,**/*.md

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.exclusions=**/*_test.go,\
main.go,\
cmd/docs.go,cmd/completion.go,cmd/upgrade.go,\
cmd/root.go,cmd/pull.go,cmd/list.go,\
cmd/db.go,cmd/doctor.go,cmd/fork.go,cmd/script.go,\
cmd/clean.go,\
cmd/run.go,cmd/tunnel.go,\
cmd/notifications.go,\
utils/art/**,utils/messages.go,utils/getRandomQuote.go,\
utils/proc_default.go,utils/proc_windows.go,\
utils/sendInterrupt_default.go,utils/sendInterrupt_windows.go,\
utils/startCommands.go,\
utils/storage.go,\
utils/instructionsToInstallTools.go,\
utils/examples.go,\
utils/prompt.go,\
utils/docker.go,\
utils/notify.go,\
utils/dbshell.go
