db_services:
  mongodb_with_data_for_go:
    driver: mongodb
    # TODO: fix creation of database
    # databaseName: bestDbName
    user: awesomeUser
    password: themostsecurepasswordyoucanimaging
    port: 5519
    # TODO: create dump file to populate db
    # seedFromFilePath: ./users_dump.sql

services:
  go_server_listen_to_mongodb:
    cloneFrom: https://github.com/Andriiklymiuk/go_server_listen_to_mongodb.git
    port: 1202
    depends_on_db:
      - name: mongodb_with_data_for_go
        envAlias: DB
    start:
      - go run .

required:
  go:
    why:
      - To launch locally sync-go-trigger service manually
      - You need to install it yourself brew install go
    checkCmd: go version
  docker:
    why:
      - To launch databases
      - You need to install it yourself from https://docs.docker.com/desktop/install/mac-install/
    checkCmd: docker -v
