db_services:
  rabbitmq-for-go-nestjs:
    user: best_user
    password: most_secure_password
    driver: rabbitmq
    databaseName: rabbitmq-for-go-nestjs-db
    port: 4577

services:
  nestjs_rabbitmq_emitter:
    cloneFrom: https://github.com/Andriiklymiuk/nestjs_rabbitmq_emitter.git
    path: ./nestjs_rabbitmq_emitter
    port: 7856
    depends_on_db:
      - name: rabbitmq-for-go-nestjs
    beforeStart:
      - pnpm install
    start:
      - pnpm start:dev
  go_rabbitmq_listener:
    cloneFrom: https://github.com/Andriiklymiuk/go_rabbitmq_listener.git
    path: ./go_rabbitmq_listener
    port: 7854
    depends_on_db:
      - name: rabbitmq-for-go-nestjs
    beforeStart:
      - go run .

required:
  go:
    why:
      - To launch locally sync-go-trigger service manually
      - You need to install it yourself brew install go
    checkCmd: go version
  pnpm:
    why:
      - To launch products service locally
    install:
      - brew install pnpm
    checkCmd: pnpm -v
  docker:
    why:
      - To launch databases
      - You need to install it yourself from https://docs.docker.com/desktop/install/mac-install/
    checkCmd: docker -v
