db_services:
  corgi:
    databaseName: corgi-database
    user: corgi
    password: corgiSecurePassword
    port: 5432
  corgiTest:
    databaseName: corgi-database-test
    user: corgi
    password: corgiSecurePasswordTest
    port: 5433

services:
  corgiServer:
    beforeStart:
      - echo "beforeStart example cmd 1 for corgiServer"
      - echo "beforeStart example cmd 2 for corgiServer"
    start:
      - echo "start example cmd 1 for corgiServer"
      - echo "start example cmd 2 for corgiServer"
      - echo "start example cmd 3 for corgiServer"
    afterStart:
      - echo "afterStart example cmd 1 for corgiServer"
      - echo "afterStart example cmd 2 for corgiServer"
  corgiApp:
    beforeStart:
      - echo "beforeStart example cmd 1 for corgiApp"
      - echo "beforeStart example cmd 2 for corgiApp"
    start:
      - echo "start example cmd 1 for corgiApp"
      - echo "start example cmd 2 for corgiApp"
      - echo "start example cmd 3 for corgiApp"
    afterStart:
      - echo "afterStart example cmd 1 for corgiApp"
      - echo "afterStart example cmd 2 for corgiApp"
