package utils

const (
	ErrPortConflict     = "E_PORT_CONFLICT"
	ErrDanglingDep      = "E_DANGLING_DEP"
	ErrDependencyCycle  = "E_DEPENDENCY_CYCLE"
	ErrUnknownDriver    = "E_UNKNOWN_DRIVER"
	ErrMissingStart     = "E_MISSING_START"
	ErrMissingField     = "E_MISSING_FIELD"
	ErrComposeNotFound  = "E_COMPOSE_NOT_FOUND"
	ErrComposeParse     = "E_COMPOSE_PARSE"
	ErrServiceNotFound  = "E_SERVICE_NOT_FOUND"
	ErrInteractiveReq   = "E_INTERACTIVE_REQUIRED"
	ErrUnhealthy        = "E_UNHEALTHY"
	ErrReadinessTimeout = "E_READINESS_TIMEOUT"
	ErrDockerDown       = "E_DOCKER_DOWN"
	ErrUsage            = "E_USAGE"
	ErrExecFailed       = "E_EXEC_FAILED"
	ErrUnknownProfile   = "E_UNKNOWN_PROFILE"
	ErrInvalidCondition = "E_INVALID_CONDITION"
	ErrConfig           = "E_CONFIG"
	ErrAlreadyRunning   = "E_ALREADY_RUNNING"
	ErrUnsupported      = "E_UNSUPPORTED"
	ErrNotRunning       = "E_NOT_RUNNING"
	ErrConfigPath       = "E_CONFIG_PATH"
	ErrConfigRead       = "E_CONFIG_READ"
	ErrDuplicateName    = "E_DUPLICATE_NAME"
	ErrPortRange        = "E_PORT_RANGE"
)
