package utils

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

type GitLabCacheOptions struct {
	PathPrefix string
}

const (
	gitlabMaxCaches      = 4
	gitlabCacheTemplate  = ".corgi-cache"
	gitlabHomeCacheRoot  = ".corgi-cache"
	gitlabMergedGroupKey = "mixed"
)

type gitlabHomeCache struct {
	env string
	dir string
}

var gitlabHomeCaches = map[string]gitlabHomeCache{
	"~/.npm":                    {"npm_config_cache", "npm"},
	"~/.bun/install/cache":      {"BUN_INSTALL_CACHE_DIR", "bun"},
	"~/.cache/yarn":             {"YARN_CACHE_FOLDER", "yarn"},
	"~/.local/share/pnpm/store": {"npm_config_store_dir", "pnpm"},
	"~/.cache/pip":              {"PIP_CACHE_DIR", "pip"},
	"~/.cache/uv":               {"UV_CACHE_DIR", "uv"},
	"~/.cache/pypoetry":         {"POETRY_CACHE_DIR", "poetry"},
	"~/.cache/pipenv":           {"PIPENV_CACHE_DIR", "pipenv"},
	"~/go/pkg/mod":              {"GOMODCACHE", "go-mod"},
	"~/.cargo/registry":         {"CARGO_HOME", "cargo"},
	"~/.cargo/git":              {"CARGO_HOME", "cargo"},
	"~/.composer/cache":         {"COMPOSER_CACHE_DIR", "composer"},
	"~/.hex":                    {"HEX_HOME", "hex"},
	"~/.pub-cache":              {"PUB_CACHE", "pub"},
}

type gitlabEntry struct {
	id    string
	paths []string
}

func GitLabCacheYAML(plan CachePlan, opts GitLabCacheOptions) string {
	entries := gitlabEntries(plan, opts)

	var b strings.Builder
	b.WriteString("# Generated by `corgi cache paths --gitlab`. Do not edit by hand.\n")
	b.WriteString("# Regenerate whenever a service or its cacheKey changes; CI guards it with\n")
	b.WriteString("#   corgi cache paths --gitlab --check .gitlab/corgi-cache.yml\n")
	b.WriteString("#\n")
	b.WriteString("# Paths are project-relative because GitLab cannot cache anything outside the\n")
	b.WriteString("# project directory. The variables below move each package manager's shared\n")
	b.WriteString("# cache in there, so they must also be in effect while the install runs —\n")
	b.WriteString("# extend " + gitlabCacheTemplate + " on the job that runs corgi, not on a warming job alone.\n")
	b.WriteString("#\n")
	b.WriteString("# The keys are branch-scoped rather than hashed from the lockfiles: corgi\n")
	b.WriteString("# clones the service repos during the job, so no lockfile exists yet when\n")
	b.WriteString("# GitLab would compute a key:files. A warm-but-stale restore is safe anyway —\n")
	b.WriteString("# corgi re-hashes each cacheKey and re-checks that the dependency directory is\n")
	b.WriteString("# really there before skipping an install, so the worst case is a reinstall,\n")
	b.WriteString("# never a service started against packages that are not present.\n")

	if len(plan.Groups) == 0 {
		b.WriteString("#\n")
		b.WriteString("# No service declares a beforeStart cacheKey, so only corgi's step markers\n")
		b.WriteString("# are cached and every install runs from scratch. Add a cacheKey to each\n")
		b.WriteString("# install step and regenerate to get real caching:\n")
		if len(plan.Hints) > 0 {
			for _, line := range CacheHintLines(plan.Hints) {
				b.WriteString("#   " + line + "\n")
			}
		} else {
			b.WriteString("#   beforeStart:\n")
			b.WriteString("#     - run: npm ci\n")
			b.WriteString("#       cacheKey: [package-lock.json]\n")
		}
	}

	b.WriteString("\n" + gitlabCacheTemplate + ":\n")
	if vars := gitlabVariables(plan); len(vars) > 0 {
		b.WriteString("  variables:\n")
		for _, v := range vars {
			fmt.Fprintf(&b, "    %s: \"$CI_PROJECT_DIR/%s\"\n", v.env, path.Join(gitlabHomeCacheRoot, v.dir))
		}
	}
	b.WriteString("  cache:\n")
	for _, e := range entries {
		writeGitLabEntry(&b, e)
	}
	return b.String()
}

func writeGitLabEntry(b *strings.Builder, e gitlabEntry) {
	prefix := "corgi-deps-" + e.id
	fmt.Fprintf(b, "    - key: \"%s-$CI_COMMIT_REF_SLUG\"\n", prefix)
	b.WriteString("      fallback_keys:\n")
	fmt.Fprintf(b, "        - \"%s-$CI_DEFAULT_BRANCH\"\n", prefix)
	fmt.Fprintf(b, "        - \"%s\"\n", prefix)
	b.WriteString("      paths:\n")
	for _, p := range e.paths {
		b.WriteString("        - " + p + "\n")
	}
	b.WriteString("      when: always\n")
}

func gitlabEntries(plan CachePlan, opts GitLabCacheOptions) []gitlabEntry {
	if len(plan.Groups) == 0 {
		return []gitlabEntry{{id: "markers", paths: gitlabPaths(plan.Paths, opts)}}
	}

	var ecosystems, markers []gitlabEntry
	for _, g := range plan.Groups {
		e := gitlabEntry{id: g.ID, paths: gitlabPaths(g.Paths, opts)}
		if g.ID == "markers" {
			markers = append(markers, e)
			continue
		}
		ecosystems = append(ecosystems, e)
	}

	if room := gitlabMaxCaches - len(markers); len(ecosystems) > room && room > 0 {
		merged := gitlabEntry{id: gitlabMergedGroupKey}
		for _, e := range ecosystems[room-1:] {
			merged.paths = append(merged.paths, e.paths...)
		}
		merged.paths = dedupeSorted(merged.paths)
		ecosystems = append(ecosystems[:room-1], merged)
	}
	return append(ecosystems, markers...)
}

func gitlabPaths(paths []string, opts GitLabCacheOptions) []string {
	out := make([]string, 0, len(paths))
	seen := map[string]bool{}
	for _, p := range paths {
		mapped, isHome := gitlabHomeCaches[p]
		switch {
		case isHome:
			p = path.Join(gitlabHomeCacheRoot, mapped.dir)
		case strings.HasPrefix(p, "~/"):
			continue
		default:
			p = gitlabPrefix(p, opts)
		}
		if seen[p] {
			continue
		}
		seen[p] = true
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

func gitlabPrefix(p string, opts GitLabCacheOptions) string {
	if opts.PathPrefix == "" {
		return p
	}
	return path.Join(opts.PathPrefix, p)
}

type gitlabVariable struct{ env, dir string }

func gitlabVariables(plan CachePlan) []gitlabVariable {
	seen := map[string]gitlabVariable{}
	for _, p := range plan.Paths {
		if mapped, ok := gitlabHomeCaches[p]; ok {
			seen[mapped.env] = gitlabVariable(mapped)
		}
	}
	out := make([]gitlabVariable, 0, len(seen))
	for _, v := range seen {
		out = append(out, v)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].env < out[j].env })
	return out
}

func dedupeSorted(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, v := range in {
		if seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}
