package utils

import (
	"fmt"
	"path"
	"sort"
	"strings"
)

// GitLabCacheOptions tunes the generated cache config for where the compose
// file sits relative to the GitLab project root.
type GitLabCacheOptions struct {
	// PathPrefix is prepended to every compose-relative path. A pipeline that
	// clones the workspace repo into a subdirectory needs it, because GitLab
	// resolves cache paths against the project root and nothing else.
	PathPrefix string
}

// GitLab's own limits, which are what force most of the shape below.
const (
	gitlabMaxCaches      = 4
	gitlabCacheTemplate  = ".corgi-cache"
	gitlabHomeCacheRoot  = ".corgi-cache"
	gitlabMergedGroupKey = "mixed"
)

// gitlabHomeCache redirects a package manager's shared cache into the project.
// GitLab's caches "define their paths relative to the project directory, and
// can't link to files outside it", so corgi's "~/..." entries are uncacheable
// as they stand; each becomes an in-project directory plus the environment
// variable that puts the package manager's cache there.
type gitlabHomeCache struct {
	env string
	dir string
}

// Only true caches belong here. GEM_HOME, for one, is where gems install
// rather than where they are cached, so redirecting it would move the install
// and can break a later bundle exec — ruby's in-project vendor/bundle is the
// part worth caching anyway.
var gitlabHomeCaches = map[string]gitlabHomeCache{
	"~/.npm":                    {"npm_config_cache", "npm"},
	"~/.bun/install/cache":      {"BUN_INSTALL_CACHE_DIR", "bun"},
	"~/.cache/yarn":             {"YARN_CACHE_FOLDER", "yarn"},
	"~/.local/share/pnpm/store": {"npm_config_store_dir", "pnpm"},
	"~/.cache/pip":              {"PIP_CACHE_DIR", "pip"},
	"~/.cache/uv":               {"UV_CACHE_DIR", "uv"},
	"~/.cache/pypoetry":         {"POETRY_CACHE_DIR", "poetry"},
	"~/.cache/pipenv":           {"PIPENV_CACHE_DIR", "pipenv"},
	"~/go/pkg/mod":              {"GOMODCACHE", "go-mod"},
	"~/.cargo/registry":         {"CARGO_HOME", "cargo"},
	"~/.cargo/git":              {"CARGO_HOME", "cargo"},
	"~/.composer/cache":         {"COMPOSER_CACHE_DIR", "composer"},
	"~/.hex":                    {"HEX_HOME", "hex"},
	"~/.pub-cache":              {"PUB_CACHE", "pub"},
}

// gitlabEntry is one rendered cache entry.
type gitlabEntry struct {
	id    string
	paths []string
}

// GitLabCacheYAML renders the cache plan as a GitLab CI config fragment: a
// hidden `.corgi-cache` job template that a real job extends.
//
// GitHub reads the plan at runtime through the action's outputs. GitLab cannot
// — its cache config is static YAML — so the fragment is generated and
// committed, and `corgi cache paths --gitlab --check` fails once it stops
// matching the compose file.
func GitLabCacheYAML(plan CachePlan, opts GitLabCacheOptions) string {
	entries := gitlabEntries(plan, opts)

	var b strings.Builder
	b.WriteString("# Generated by `corgi cache paths --gitlab`. Do not edit by hand.\n")
	b.WriteString("# Regenerate whenever a service or its cacheKey changes; CI guards it with\n")
	b.WriteString("#   corgi cache paths --gitlab --check .gitlab/corgi-cache.yml\n")
	b.WriteString("#\n")
	b.WriteString("# Paths are project-relative because GitLab cannot cache anything outside the\n")
	b.WriteString("# project directory. The variables below move each package manager's shared\n")
	b.WriteString("# cache in there, so they must also be in effect while the install runs —\n")
	b.WriteString("# extend " + gitlabCacheTemplate + " on the job that runs corgi, not on a warming job alone.\n")
	b.WriteString("#\n")
	b.WriteString("# The keys are branch-scoped rather than hashed from the lockfiles: corgi\n")
	b.WriteString("# clones the service repos during the job, so no lockfile exists yet when\n")
	b.WriteString("# GitLab would compute a key:files. A warm-but-stale restore is safe anyway —\n")
	b.WriteString("# corgi re-hashes each cacheKey and re-checks that the dependency directory is\n")
	b.WriteString("# really there before skipping an install, so the worst case is a reinstall,\n")
	b.WriteString("# never a service started against packages that are not present.\n")

	if len(plan.Groups) == 0 {
		b.WriteString("#\n")
		b.WriteString("# No service declares a beforeStart cacheKey, so only corgi's step markers\n")
		b.WriteString("# are cached and every install runs from scratch. Add a cacheKey to each\n")
		b.WriteString("# install step and regenerate to get real caching:\n")
		b.WriteString("#   beforeStart:\n")
		b.WriteString("#     - run: npm ci\n")
		b.WriteString("#       cacheKey: [package-lock.json]\n")
	}

	b.WriteString("\n" + gitlabCacheTemplate + ":\n")
	if vars := gitlabVariables(plan); len(vars) > 0 {
		b.WriteString("  variables:\n")
		for _, v := range vars {
			fmt.Fprintf(&b, "    %s: \"$CI_PROJECT_DIR/%s\"\n", v.env, path.Join(gitlabHomeCacheRoot, v.dir))
		}
	}
	b.WriteString("  cache:\n")
	for _, e := range entries {
		writeGitLabEntry(&b, e)
	}
	return b.String()
}

func writeGitLabEntry(b *strings.Builder, e gitlabEntry) {
	prefix := "corgi-deps-" + e.id
	fmt.Fprintf(b, "    - key: \"%s-$CI_COMMIT_REF_SLUG\"\n", prefix)
	// A new branch starts from the default branch's cache instead of from
	// nothing, which is where the first run of every merge request would
	// otherwise pay the full install.
	b.WriteString("      fallback_keys:\n")
	fmt.Fprintf(b, "        - \"%s-$CI_DEFAULT_BRANCH\"\n", prefix)
	fmt.Fprintf(b, "        - \"%s\"\n", prefix)
	b.WriteString("      paths:\n")
	for _, p := range e.paths {
		b.WriteString("        - " + p + "\n")
	}
	// Saved even when the job fails: a red e2e run still installed everything,
	// and throwing that away makes the next attempt pay for it again.
	b.WriteString("      when: always\n")
}

// gitlabEntries turns the plan's groups into at most four cache entries, which
// is all GitLab allows per job. The markers entry always survives the merge:
// it is small, and it is what lets corgi skip an unchanged install at all.
func gitlabEntries(plan CachePlan, opts GitLabCacheOptions) []gitlabEntry {
	if len(plan.Groups) == 0 {
		return []gitlabEntry{{id: "markers", paths: gitlabPaths(plan.Paths, opts)}}
	}

	var ecosystems, markers []gitlabEntry
	for _, g := range plan.Groups {
		e := gitlabEntry{id: g.ID, paths: gitlabPaths(g.Paths, opts)}
		if g.ID == "markers" {
			markers = append(markers, e)
			continue
		}
		ecosystems = append(ecosystems, e)
	}

	// One slot belongs to the markers, so the ecosystems share what is left.
	// Merging the tail keeps the first ecosystems independently keyed rather
	// than dropping any of them from the cache entirely.
	if room := gitlabMaxCaches - len(markers); len(ecosystems) > room && room > 0 {
		merged := gitlabEntry{id: gitlabMergedGroupKey}
		for _, e := range ecosystems[room-1:] {
			merged.paths = append(merged.paths, e.paths...)
		}
		merged.paths = dedupeSorted(merged.paths)
		ecosystems = append(ecosystems[:room-1], merged)
	}
	return append(ecosystems, markers...)
}

func gitlabPaths(paths []string, opts GitLabCacheOptions) []string {
	out := make([]string, 0, len(paths))
	seen := map[string]bool{}
	for _, p := range paths {
		mapped, isHome := gitlabHomeCaches[p]
		switch {
		case isHome:
			p = path.Join(gitlabHomeCacheRoot, mapped.dir)
		case strings.HasPrefix(p, "~/"):
			// An ecosystem corgi knows but this table does not. Dropping it is
			// the only honest option: GitLab would reject the path outright.
			continue
		default:
			p = gitlabPrefix(p, opts)
		}
		if seen[p] {
			continue
		}
		seen[p] = true
		out = append(out, p)
	}
	sort.Strings(out)
	return out
}

func gitlabPrefix(p string, opts GitLabCacheOptions) string {
	if opts.PathPrefix == "" {
		return p
	}
	return path.Join(opts.PathPrefix, p)
}

type gitlabVariable struct{ env, dir string }

// gitlabVariables is the set of redirects the plan actually needs, so a node
// workspace does not carry a cargo variable it never reads.
func gitlabVariables(plan CachePlan) []gitlabVariable {
	seen := map[string]gitlabVariable{}
	for _, p := range plan.Paths {
		if mapped, ok := gitlabHomeCaches[p]; ok {
			seen[mapped.env] = gitlabVariable{mapped.env, mapped.dir}
		}
	}
	out := make([]gitlabVariable, 0, len(seen))
	for _, v := range seen {
		out = append(out, v)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].env < out[j].env })
	return out
}

func dedupeSorted(in []string) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(in))
	for _, v := range in {
		if seen[v] {
			continue
		}
		seen[v] = true
		out = append(out, v)
	}
	sort.Strings(out)
	return out
}
