package utils

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"gopkg.in/yaml.v3"
)

const MemoryDirName = ".corgi/memory"

var typeDirs = []struct{ Type, Dir string }{
	{"decision", "decisions"},
	{"incident", "incidents"},
	{"domain", "domain"},
	{"fix", "fixes"},
}

type Fact struct {
	Name        string   `json:"name" yaml:"name"`
	Description string   `json:"description" yaml:"description"`
	Type        string   `json:"type" yaml:"type"`
	Service     string   `json:"service,omitempty" yaml:"service,omitempty"`
	Created     string   `json:"created,omitempty" yaml:"created,omitempty"`
	Pattern     string   `json:"pattern,omitempty" yaml:"pattern,omitempty"`
	Links       []string `json:"links,omitempty" yaml:"links,omitempty"`
	Body        string   `json:"-" yaml:"-"`
	Path        string   `json:"path" yaml:"-"`
}

var (
	frontmatterRe = regexp.MustCompile(`(?s)^---\n(.*?)\n---\n?(.*)$`)
	linkRe        = regexp.MustCompile(`\[\[([^\]]+)\]\]`)
)

func typeForDir(dir string) string {
	for _, td := range typeDirs {
		if td.Dir == dir {
			return td.Type
		}
	}
	return ""
}

func typeRank(t string) int {
	for i, td := range typeDirs {
		if td.Type == t {
			return i
		}
	}
	return len(typeDirs)
}

func parseFact(raw []byte, path string) (Fact, error) {
	var f Fact
	m := frontmatterRe.FindSubmatch(raw)
	if m == nil {
		return f, nil
	}
	if err := yaml.Unmarshal(m[1], &f); err != nil {
		return f, err
	}
	f.Body = strings.TrimSpace(string(m[2]))
	f.Path = path
	f.Links = normalizeLinks(f.Links)
	return f, nil
}

func normalizeLinks(in []string) []string {
	out := make([]string, 0, len(in))
	for _, l := range in {
		if m := linkRe.FindStringSubmatch(l); m != nil {
			out = append(out, m[1])
		} else if l = strings.TrimSpace(l); l != "" {
			out = append(out, l)
		}
	}
	return out
}

func ReadFacts(root string) ([]Fact, error) {
	if _, err := os.Stat(root); os.IsNotExist(err) {
		return nil, nil
	}
	var facts []Fact
	for _, td := range typeDirs {
		dirFacts, err := readFactsFromTypeDir(filepath.Join(root, td.Dir), td.Dir)
		if err != nil {
			return nil, err
		}
		facts = append(facts, dirFacts...)
	}
	sort.SliceStable(facts, func(i, j int) bool {
		if ri, rj := typeRank(facts[i].Type), typeRank(facts[j].Type); ri != rj {
			return ri < rj
		}
		return facts[i].Name < facts[j].Name
	})
	return facts, nil
}

func readFactsFromTypeDir(dir, typeDir string) ([]Fact, error) {
	entries, err := os.ReadDir(dir)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	var facts []Fact
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".md") {
			continue
		}
		f, err := readFactFile(filepath.Join(dir, e.Name()), typeDir)
		if err != nil {
			return nil, err
		}
		facts = append(facts, f)
	}
	return facts, nil
}

func readFactFile(path, typeDir string) (Fact, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return Fact{}, err
	}
	f, err := parseFact(raw, path)
	if err != nil {
		return Fact{}, err
	}
	if f.Type == "" {
		f.Type = typeForDir(typeDir)
	}
	return f, nil
}

func dirForType(t string) (string, bool) {
	for _, td := range typeDirs {
		if td.Type == t {
			return td.Dir, true
		}
	}
	return "", false
}

func AddFact(root string, f Fact) (string, error) {
	dir, ok := dirForType(f.Type)
	if !ok {
		return "", fmt.Errorf("unknown memory type %q (want decision|incident|domain|fix)", f.Type)
	}
	if f.Name == "" {
		return "", fmt.Errorf("fact name is required")
	}
	if f.Created == "" {
		f.Created = time.Now().UTC().Format("2006-01-02")
	}
	full := filepath.Join(root, dir)
	if err := os.MkdirAll(full, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(full, f.Name+".md")
	var b strings.Builder
	b.WriteString("---\n")
	enc := yaml.NewEncoder(&b)
	enc.SetIndent(2)
	if err := enc.Encode(frontmatterOf(f)); err != nil {
		return "", err
	}
	_ = enc.Close()
	b.WriteString("---\n\n")
	if f.Body != "" {
		b.WriteString(f.Body)
		b.WriteByte('\n')
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}

func frontmatterOf(f Fact) map[string]any {
	m := map[string]any{"name": f.Name, "description": f.Description, "type": f.Type}
	if f.Service != "" {
		m["service"] = f.Service
	}
	if f.Created != "" {
		m["created"] = f.Created
	}
	if f.Pattern != "" {
		m["pattern"] = f.Pattern
	}
	if len(f.Links) > 0 {
		wrapped := make([]string, len(f.Links))
		for i, l := range f.Links {
			wrapped[i] = "[[" + l + "]]"
		}
		m["links"] = wrapped
	}
	return m
}

func RenderIndex(facts []Fact) string {
	var b strings.Builder
	b.WriteString("<!-- generated by `corgi memory index` — do not edit by hand -->\n")
	b.WriteString("# Workspace memory\n\n")
	b.WriteString(fmt.Sprintf("_%d facts · generated %s_\n", len(facts), time.Now().UTC().Format("2006-01-02")))
	lastType := ""
	for _, f := range facts {
		if f.Type != lastType {
			b.WriteString(fmt.Sprintf("\n## %s\n", pluralType(f.Type)))
			lastType = f.Type
		}
		svc := ""
		if f.Service != "" {
			svc = fmt.Sprintf(" (%s)", f.Service)
		}
		dir, _ := dirForType(f.Type)
		b.WriteString(fmt.Sprintf("- **%s**%s — %s → `%s/%s.md`\n", f.Name, svc, f.Description, dir, f.Name))
	}
	return b.String()
}

func pluralType(t string) string {
	if d, ok := dirForType(t); ok {
		return d
	}
	return t
}

type MemoryIssue struct {
	Code    string `json:"code"`
	Message string `json:"message"`
	File    string `json:"file"`
}

const (
	ErrMemorySecret       = "E_MEMORY_SECRET"
	ErrMemoryTypeMismatch = "E_MEMORY_TYPE_MISMATCH"
	ErrMemoryBadName      = "E_MEMORY_BAD_NAME"
	ErrMemoryNoFront      = "E_MEMORY_NO_FRONTMATTER"
	ErrMemoryDanglingLink = "E_MEMORY_DANGLING_LINK"
)

var (
	kebabRe   = regexp.MustCompile(`^[a-z0-9]+(-[a-z0-9]+)*$`)
	awsKeyRe  = regexp.MustCompile(`\bAKIA[0-9A-Z]{16}\b`)
	pemRe     = regexp.MustCompile(`-----BEGIN [A-Z ]*PRIVATE KEY-----`)
	assignRe  = regexp.MustCompile(`(?i)(password|secret|token|api[_-]?key|access[_-]?key)\s*[:=]\s*\S{6,}`)
	urlCredRe = regexp.MustCompile(`[a-z]+://[^/\s:@]+:[^/\s@]+@`)
)

func scanSecrets(text string) bool {
	return awsKeyRe.MatchString(text) || pemRe.MatchString(text) ||
		assignRe.MatchString(text) || urlCredRe.MatchString(text)
}

func LintFacts(root string) ([]MemoryIssue, []MemoryIssue) {
	var errs, warns []MemoryIssue
	facts, err := ReadFacts(root)
	if err != nil {
		return []MemoryIssue{{Code: ErrMemoryNoFront, Message: err.Error()}}, nil
	}
	names := make(map[string]bool, len(facts))
	for _, f := range facts {
		names[f.Name] = true
	}
	for _, f := range facts {
		factErrs, factWarns := lintFact(f, names)
		errs = append(errs, factErrs...)
		warns = append(warns, factWarns...)
	}
	errs = append(errs, scanStoreForSecrets(root)...)
	return errs, warns
}

func lintFact(f Fact, names map[string]bool) ([]MemoryIssue, []MemoryIssue) {
	rel := f.Path
	dir := filepath.Base(filepath.Dir(f.Path))
	if f.Name == "" || f.Description == "" {
		return []MemoryIssue{{ErrMemoryNoFront, "missing name/description frontmatter", rel}}, nil
	}
	var errs, warns []MemoryIssue
	stem := strings.TrimSuffix(filepath.Base(f.Path), ".md")
	if f.Name != stem || !kebabRe.MatchString(f.Name) {
		errs = append(errs, MemoryIssue{ErrMemoryBadName, "name must be kebab-case and match the filename", rel})
	}
	if want := typeForDir(dir); want != "" && f.Type != want {
		errs = append(errs, MemoryIssue{ErrMemoryTypeMismatch,
			fmt.Sprintf("type %q in %s/ (want %q)", f.Type, dir, want), rel})
	}
	for _, l := range f.Links {
		if !names[l] {
			warns = append(warns, MemoryIssue{ErrMemoryDanglingLink,
				fmt.Sprintf("[[%s]] has no matching fact", l), rel})
		}
	}
	return errs, warns
}

func scanStoreForSecrets(root string) []MemoryIssue {
	var errs []MemoryIssue
	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), ".md") {
			return nil
		}
		raw, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if scanSecrets(string(raw)) {
			errs = append(errs, MemoryIssue{ErrMemorySecret,
				"a secret-shaped string is present — committed memory must never hold secrets", path})
		}
		return nil
	})
	if err != nil && !os.IsNotExist(err) {
		errs = append(errs, MemoryIssue{ErrMemorySecret, err.Error(), root})
	}
	return errs
}
