name: Create Tag

on:
  push:
    branches:
      - "*"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run make getActionVersion
        run: make getActionVersion

      - name: Extract APP_VERSION and Create Tag
        run: |
          TAG="v${VERSION}"

          echo "VERSION: ${VERSION}"
          echo "TAG: $TAG"

          # Check if the tag exists
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/$TAG)

          if [ "$HTTP_STATUS" -ne 200 ]
          then
            echo "Tag does not exist, creating new tag"
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git tag $TAG
            git push origin $TAG
          else
            echo "Tag already exists"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
