name: Create Tag

on:
  push:
    branches:
      - "main"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run make getActionVersion
        run: make getActionVersion

      - name: Extract APP_VERSION and Create Tag
        id: create-tag
        run: |
          TAG="v${VERSION}"

          echo "VERSION: ${VERSION}"
          echo "TAG: $TAG"

          # Check if the tag exists
          EXISTS=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/$TAG)

          if [ "$EXISTS" == "null" ]
          then
            echo "Tag does not exist, creating new tag"
            git tag $TAG
            git push origin $TAG
            echo "::set-output name=tag_exists::false"
          else
            echo "Tag already exists"
            echo "::set-output name=tag_exists::true"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Trigger Release workflow
        if: steps.create-tag.outputs.tag_exists == 'false'
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yml/dispatches \
            -d '{"ref":"refs/tags/'"$TAG"'"}'
