name: Create Tag

on:
  push:
    branches:
      - "main"

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run make getActionVersion
        run: make getActionVersion

      - name: Extract APP_VERSION and Create Tag
        id: create-tag
        run: |
          TAG="v${VERSION}"

          echo "VERSION: ${VERSION}"
          echo "TAG: $TAG"

          # Check if the tag exists
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/${GITHUB_REPOSITORY}/git/ref/tags/$TAG)

          if [ "$HTTP_STATUS" -ne 200 ]
          then
            echo "Tag does not exist, creating new tag"
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git tag $TAG
            git push origin $TAG
            echo "TAG_EXISTS=false" >> $GITHUB_ENV
          else
            echo "Tag already exists"
            echo "TAG_EXISTS=true" >> $GITHUB_ENV
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Trigger Release workflow
        if: env.TAG_EXISTS == 'false'
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/release.yml/dispatches \
            -d '{"ref":"refs/tags/'"$TAG"'"}'
